### ISSUE TITLE
no link when its title is blank

### ISSUE THREAD

**Issue by LWisteria** [nanonanomachine/radvent#32]
If title is blank
![blank](https://cloud.githubusercontent.com/assets/10543208/11945456/46099c14-a893-11e5-84f0-639065a1ce78.PNG)
we get nothing on the top page.
![nolink](https://cloud.githubusercontent.com/assets/10543208/11945455/46009ad8-a893-11e5-8bd9-7d09ff4cb64c.PNG)
Therefore there's no way to reach the item, including to edit to input its title.
The HTML source is shown below.
```html
<td>
<p class="advent-calendar-date">
1
</p>
<p class="text-info advent-calendar-author">
yoshifujiさん
</p>
<p class="text-info advent-calendar-entry">
<a href="/items/1"></a>
</p>
</td>
```
I could get the link from the HTML source and modified its title....

Is it possible to show <a> tag's text nothing but some text (e.g. "No title" or "無題") if its title is blank?

Sorry for I cannot modify by myself and send pull request because I'm not good at Ruby (RoR).
And thanks for this very nice system!

**Comment by nanonanomachine** [comment]
This issue just happened with my company's intranet advent calendar yesterday.
I'll fix it ASAP, maybe tommorow.

Thanks for reporting the issue :+1:

**Comment by nanonanomachine** [comment]
I fixed it !

Japanese locale:

![image](https://cloud.githubusercontent.com/assets/1884908/12046928/362946c2-af06-11e5-8908-657924decd9c.png)

English locale:

![image](https://cloud.githubusercontent.com/assets/1884908/12046953/66120838-af06-11e5-8e7c-981cdd4c6c4f.png)

Please pull latest change which fixes this issue.
