### ISSUE TITLE
Jump to item page when published page's cancel button pushed

### ISSUE THREAD

**Issue by kyow** [nanonanomachine/radvent#35]
If unpublished edit page's cancel button pushed, jump to information page.
It's good.
But I think, if published edit page's cancel button pushed, it must  jump to item page.
(Please fix to correct English.)

**Comment by nanonanomachine** [comment]
>But I think, if published edit page's cancel button pushed, it must jump to item page.

I agree it should jump back the transition source page when we press cancel button.
